# Generated by Django 4.1 on 2023-10-04 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_name', models.CharField(max_length=80, verbose_name='Meal Type')),
                ('meal_carbohydrates_level', models.CharField(max_length=80, verbose_name='Carb level')),
                ('meal_protein_level', models.CharField(max_length=80, verbose_name='Protein level')),
                ('meal_fats_level', models.CharField(max_length=80, verbose_name='Fats level')),
                ('meal_cal_level', models.CharField(max_length=80, verbose_name='Calories level')),
                ('meal_mg_level', models.CharField(max_length=80, verbose_name='Mg level')),
                ('meal_na_level', models.CharField(max_length=80, verbose_name='Na level')),
                ('meal_chol_level', models.CharField(max_length=80, verbose_name='Cholesterol level')),
            ],
        ),
    ]
