# Generated by Django 4.1 on 2023-10-04 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calorieapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='meal_cal_level',
            field=models.IntegerField(verbose_name='Calories level'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='meal_carbohydrates_level',
            field=models.FloatField(verbose_name='Carb level'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='meal_chol_level',
            field=models.FloatField(max_length=80, verbose_name='Cholesterol level'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='meal_fats_level',
            field=models.FloatField(verbose_name='Fats level'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='meal_mg_level',
            field=models.FloatField(max_length=80, verbose_name='Mg level'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='meal_na_level',
            field=models.FloatField(max_length=80, verbose_name='Na level'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='meal_protein_level',
            field=models.FloatField(verbose_name='Protein level'),
        ),
    ]
