# Generated by Django 4.1 on 2023-10-05 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calorieapp', '0003_consumed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumed',
            name='date_added',
            field=models.DateTimeField(),
        ),
    ]
