# Generated by Django 4.1 on 2023-10-05 01:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calorieapp', '0004_alter_consumed_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumed',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 5, 2, 49, 39, 843715)),
        ),
    ]
